version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "docker"
      - "dependencies"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "python"
      - "dependencies"
    ignore:
      - dependency-name: "numpy"
        versions: ["2.0.0", "2.*", "3.*"]
      - dependency-name: "tensorflow"
        versions: ["3.0.0", "3.*"]
      - dependency-name: "pillow"
        versions: ["11.0.0", "11.*"]
      - dependency-name: "pydantic"
        versions: ["3.0.0", "3.*"]
      - dependency-name: "fastapi"
        versions: ["1.0.0", "1.*"]
      - dependency-name: "starlette"
        versions: ["1.0.0", "1.*"]
      - dependency-name: "uvicorn"
        versions: ["1.0.0", "1.*"]
    commit-message:
      prefix: "pip"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "actions"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"